### PR TITLE
F/envision

### PR DESCRIPTION
**Pull request by bjonkman**
Latest Envision commits, including 
- DBEMT (AeroDyn)
- BeamDyn output nodes at trapezoidal quadrature points (Gaussian quadrature still uses the FE nodes)
- BeamDyn quasi-steady start option
- BeamDyn linearization

I updated the input files for r-test (not included here) and updated documentation regarding the input file changes. I did not run the BD unit tests as I couldn't get it to build with cmake on Windows, yet.

### CODE REVIEW

**Comment by bjonkman** [comment]
By the way, when these are merged in, you can close https://github.com/OpenFAST/openfast/issues/81 and https://github.com/OpenFAST/openfast/issues/80.

**Comment by bjonkman** [comment]
FYI, here is a flow chart that explains the AeroDyn logic flow: [AeroDyn-flowchart.pdf](https://github.com/rafmudaf/openfast/files/2095761/AeroDyn-flowchart.pdf). I have a .fodg (xml OpenDocument Drawing file) if you'd like that, but GitHub won't allow me to attach that format here. I could perhaps add it to the docs folder in the repo. Let me know.

**Comment by rafmudaf** [comment]
Excellent, thank you

**Comment by rafmudaf** [comment]
@bjonkman I rebased your r-test branch above onto the current top of `openfast/r-test`. You can see it at https://github.com/OpenFAST/r-test/tree/pullrequest/bjonkman.

FYI the current head of the `openfast/r-test` repository is not called `dev` but instead `openfast/50e77916`. This naming scheme ensures that a commit hash in r-test that is linked to a commit in openfast will always exist (so long as no one deletes a branch in the `openfast/` name space).

**Comment by rafmudaf** [comment]
@bjonkman @jjonkman where can I find these linearization regression test cases: fixed-free beam, free-free beam, and Campbell diagram?

**Comment by rafmudaf** [comment]
@bjonkman Currently, one of the BeamDyn unit tests is failing on this branch: `test_BD_InputGlobalLocal`. The reason for this is that this unit test verifies that these quantities are appropriately rotated in `BD_InputGlobalLocal`:
```
    ! Check the following quanities are actually rotated
    !!  1 Displacements                -> u%RootMotion%TranslationDisp(:,1)
    !!  2 Linear/Angular velocities    -> u%RootMotion%TranslationVel(:,1), u%RootMotion%RotationVel(:,1)
    !!  3 Linear/Angular accelerations -> u%RootMotion%TranslationAcc(:,1), u%RootMotion%RotationAcc(:,1)
    !!  4 Point forces/moments         -> u%PointLoad%Force(1:3,i), u%PointLoad%Moment(1:3,i)
    !!  5 Distributed forces/moments   -> u%DistrLoad%Force(1:3,i), u%DistrLoad%Moment(1:3,i)
```
However, I noticed a commit in `f/Envision` which moves the rotation of the point and distributed loads to `BD_DistrLoadCopy`:
https://github.com/rafmudaf/openfast/pull/6/commits/fd0a1b758b44e4928f6d5c3144315d029295653c#diff-664a94ccf9adc2f99758be06faa76a84L4556.

Is it required to move these rotations to `BD_DistrLoadCopy` rather than keep them in `BD_InputGlobalLocal`? Having these rotations in the same subroutine which handles the other rotations from global to local frame enables better unit testing and improves clarity in the code. Specifically, the name `BD_InputGlobalLocal` implies some sort of mapping from global to local so its a logical place for that code, whereas `BD_DistrLoadCopy` gives no clues to that rotation. Further, the pattern of calling `BD_InputGlobalLocal` before `BD_DistrLoadCopy` throughout BeamDyn certainly reads as though the rotations occur first followed by the load copy. Moving these two specific rotations also deteriorates the separation of concerns that was initially established regarding this code.

Please let me know if there is a specific reason or functionality requiring this refactor.

**Comment by jjonkman** [comment]
Hi Raf,

I thought that you had received these earlier, but if not, here are the test cases and results that we ran for the verification of the new BeamDyn linearization functionality of OpenFAST included within the F/envision commit.

My understanding is that you already have Bonnie’s commit with the updated inputs files from the r-test based on the input file changes included in the F/envision commit.

I’ve attached LinearizationTests.zip that includes new test cases for a fixed-free and free-free beam.  Included in the archive is a MATLAB script that can run the cases and show the results.  To run this script, you’ll need to set the variable ‘FASTexe’ in the runFAST.m file, and you will need to have the newest matlab-toolbox with the mbc submodule on your matlab path.  The results should be as shown below, where it is clear that we are compare the results from the new BeamDyn linearization functionality in OpenFAST, with results from the Analytical solution and (for the fixed-free beam) results derived from the mass and stiffness matrices reported in the BeamDyn summary file.  The small differences between the linearization result and the analytical result are the result of small differences in the model formulation.  You can add both of these tests to the r-test.

       Analytical     Linearization   BD Summary File
----------------- ----------------- -----------------
* Fixed-Free Beam:
           0.5842            0.5710            0.5699
           0.5842            0.5710            0.5699
           3.6607            3.5462            3.5460
           3.6607            3.5462            3.5460
          10.2512            9.7639            9.7640
          10.2512            9.7639            9.7640
     .............. # rigid body modes .............. 
                0                 0                 0

* Free-Free Beam:
           3.7171            3.5717
           3.7171            3.5717
          10.2465            9.5349
          10.2465            9.5349
          20.0873           18.1690
          20.0873           18.1690
     .............. # rigid body modes .............. 
                6                 2

I’ve also attached Test26_CampbellDiagram-NREL.zip that includes a test case whereby a Campbell diagram is generated using the land-based NREL 5-MW turbine using both a full ElastoDyn model and a ElastoDyn + BeamDyn model.  Included in the archive is a MATLAB script we used to run FAST several times to generate the Campbell diagrams (it runs the code for each rotor speed in steps of 2RPM from 0 to 14 RPM). The script generates MS Excel files, which are manually manipulated to identify the full-system modes.  Bonnie has additional MATLAB scripts (not provided in the attachment) that read the Excel files to produce the plots (BeamDyn.fig) and ElastoDyn.fig) shown below.  Clearly the natural frequencies agree very well between BeamDyn and ElastoDyn.  The biggest difference is in the natural frequency of the 2nd tower SS mode.  We confirmed that this difference is also seen in the time-domain solution of BeamDyn, so, is expected given the different blade dynamics between BeamDyn and ElastoDyn.  This can be seen by the PSD below, derived by running an OpenFAST with BeamDyn simulation whereby the 2nd tower SS mode in ElastoDyn is perturbed (in the code) with 10 times the 1st tower SS initial displacement of 0.01 m.  But this mode damps out quickly.  The differences in damping between BeamDyn and ElastoDyn are also expected given the differences in the structural damping formulation.  For the associated r-test, there is no reason to generate the full Campbell diagram for all rotor speeds, but it would probably be useful to add a BeamDyn test at one rotor speed.

image

image

image

We still plan to generate a Campbell diagram with aerodynamics/aero damping (as a function of wind speed instead of rotational speed), but have not had the chance to do that yet.  We’ll include all of these results with further documentation in the journal paper we are working on.

Please let me know if you have further questions.

Thanks,

[LinearizationTests.zip](https://github.com/rafmudaf/openfast/files/2237170/LinearizationTests.zip)
[Test26_CampbellDiagram-NREL.zip](https://github.com/rafmudaf/openfast/files/2237171/Test26_CampbellDiagram-NREL.zip)

**Comment by andrew-platt** [comment]
Hi Rafael,

There were two motivations for moving the distributed load rotations to the DistrLoadCopy routine.  The first was to consolidate the all the load calculation handling into one place.  In my mind it was better than having them split into two locations (the InputGlobalLocal and the DistrLoadCopy routines).

At the time I made that change, I was also looking into the option of adding an intermediate mesh point for the first node.  In the current formulation of the BeamDyn, the first node point must be at the RootMotion location at (0,0,0).  To allow for the first node position to be offset (which could correspond better to the elastic axis location which is not centered there), I added an intermediate mesh point that the first node of the first element corresponds to.  This point was then mapped over from the RootMotion mesh point.  So the second motivation was that there was some advantage to consolidating the load calculations in one place outside the InputGlobalLocal routine (the exact details are not obvious to me anymore, but I think it was related to the calling order and load ramping with the mesh mapping).  However, the intermediate mesh point led to solver instabilities and was put on hold (we may never revisit that idea).

**Comment by rafmudaf** [comment]
Thank you for the details @andrew-platt. Both motivations make sense and seem worthwhile to me. However, in order to maintain the current level of code coverage in unit tests, I propose to revert the changes regarding the input force and moment transformations **for now**.

Regarding code readability, there is a current effort at NREL to improve the design of BeamDyn in that sense (see the pull request at [openfast#143](https://github.com/OpenFAST/openfast/pull/143)). Since the unit tests are being improved and updated there at the moment, this would fit in nicely. Furthermore, an informative subroutine name, such as `BD_CalculateInputLoads` or `BD_PrepareInputLoads`, may help readability as well as support testing of this specific functionality.

And since the intermediate mesh point improvement has been put on hold, I suggest that this refactor occur if that improvement is revived and it has not been refactored already.

If you and Envision agree, I'll submit a pull request with the reverted code to @bjonkman's `f/Envision` branch and this will fix the currently failing unit test.

**Comment by bjonkman** [comment]
@rafmudaf Given the number of changes NREL has been making, I think we are just going to have divergent code bases anyway. So, go ahead and change this code as you feel is necessary.

**Pull request merged**
